name: Test workflow
on:
  workflow_call:
    inputs:
      matrix-step-name:
        required: false
        type: string
      matrix-key:
        required: false
        type: string
      in:
        required: true
        type: string
    outputs:
      result:
        description: "Result"
        value: ${{ jobs.do.outputs.result }}

jobs:
  do:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: echo "Do setup"

      - name: Checkout
        uses: actions/checkout@v3

      - uses: cloudposse/github-action-matrix-outputs-write@0.3.0
        id: writer
        with:
          matrix-step-name: ${{ inputs.matrix-step-name }}
          matrix-key: ${{ inputs.matrix-key }}
          outputs: |-
            result: ${{ inputs.in }}

    outputs:
      result: ${{ steps.writer.outputs.result }}